abbr -a .. 'cd ..'
abbr -a ... 'cd ../..'
abbr -a b bundle
abbr -a bx 'bundle exec'
abbr -a c chezmoi
abbr -a ca 'chezmoi add'
abbr -a cr 'chezmoi re-add'
abbr -a d 'git diff'
abbr -a devlog 'tail -f log/development.log'
abbr -a ds 'NO_CONFIRM=1 ./deploy staging'
abbr -a dp './deploy production'
abbr -a g git
abbr -a ga 'git add'
# abbr -a gaa     'git add --all'
# abbr -a gau     'git add --update'
abbr -a gbl 'git blame'
abbr -a gb 'git branch -vv'
abbr -a gbx 'git branch -d'
abbr -a gbX 'git branch -D'
abbr -a gco 'git checkout'
abbr -a gcb 'git checkout -b'
abbr -a gcp 'git cherry-pick'
# abbr -a gcpa      'git cherry-pick --abort'
# abbr -a gcpc      'git cherry-pick --continue'
# abbr -a gcln      'git clean -fd'
# abbr -a gcl       'git clone --recursive'
abbr -a gc 'git commit -v'
abbr -a gc! 'git commit -v --amend'
abbr -a gca 'git commit -v -a'
abbr -a gca! 'git commit -v -a --amend'
# abbr -a gcam      'git commit -a -m'
# abbr -a gcmsg     'git commit -m'
# abbr -a gcan!     'git commit -v -a --no-edit --amend'
# abbr -a gcans!    'git commit -v -a -s --no-edit --amend'
# abbr -a gcn!      'git commit -v --no-edit --amend'
# abbr -a gcs       'git commit -S'
# abbr -a gcsm      'git commit -s -m'
# abbr -a gcf       'git config --list'
# abbr -a gdct      'git describe --tags `git rev-list --tags --max-count=1`'
abbr -a d 'git diff'
# abbr -a gd        'git diff'
# abbr -a gdca      'git diff --cached'
# abbr -a gdt       'git diff-tree --no-commit-id --name-only -r'
# abbr -a gdw       'git diff --word-diff'
abbr -a gf 'git fetch'
abbr -a gfa 'git fetch --all --prune'
abbr -a gfo 'git fetch origin --prune'
# abbr -a gfix      'git diff --name-only | uniq | xargs $EDITOR'
abbr -a gm 'git merge --no-ff'
abbr -a gmf 'git merge --ff-only'
abbr -a gp 'git push'
abbr -a gpf 'git push --force-with-lease'
# abbr -a gpristine 'git reset --hard && git clean -dfx'
abbr -a gpu 'git push -u'
abbr -a grb 'git rebase'
abbr -a grba 'git rebase --abort'
abbr -a grbc 'git rebase --continue'
abbr -a grbi 'git rebase -i'
abbr -a grbm 'git rebase master'
abbr -a grbs 'git rebase --skip'
abbr -a gr 'git reset'
abbr -a grh 'git reset --hard'
abbr -a grhc 'git reset --hard && git clean -fd'
abbr -a grs 'git reset --soft'
# Install git-smart gem
abbr -a gup 'git smart-pull'
abbr -a gst 'git stash'
abbr -a gsta 'git stash apply'
abbr -a gstc 'git stash clear'
abbr -a gstd 'git stash drop'
abbr -a gstl 'git stash list'
abbr -a gsts 'git stash save'
# abbr -a gstst     'git stash show --text'
abbr -a gstp 'git stash pop'
abbr -a gstu 'git stash -u'
abbr -a s 'git status -sb'
# abbr -a gs        'git status -sb'
# abbr -a gsi       'git submodule init'
# abbr -a gsu       'git submodule update'
# abbr -a gunignore 'git update-index --no-assume-unchanged'
# abbr -a gwch      'git whatchanged -p --abbrev-commit --pretty=medium'
abbr -a hlp 'heroku logs -r production'
abbr -a hls 'heroku logs -r staging'
abbr -a hltp 'heroku logs -t -r production'
abbr -a hlts 'heroku logs -t -r staging'
abbr -a hrcp 'heroku run console -r production'
abbr -a hrcs 'heroku run console -r staging'
abbr -a lg lazygit
abbr -a pt papertrail
abbr -a rc 'bin/rails console'
abbr -a rcs 'bin/rails console --sandbox'
abbr -a rdb 'bin/rails dbconsole'
abbr -a rdm 'bin/rails db:migrate'
abbr -a rdms 'bin/rails db:migrate:status'
abbr -a rdr 'bin/rails db:rollback'
abbr -a reload 'source ~/.config/fish/config.fish'
abbr -a rlc 'bin/rails log:clear'
abbr -a rr 'bin/rails routes'
abbr -a rrg 'bin/rails routes | grep'
abbr -a rt 'bin/rails test'
abbr -a rta 'bin/rails test:all'
abbr -a rtm 'bin/rails test:models'
abbr -a rts 'bin/rails test:system'
abbr -a sp 'bundle exec rspec'
abbr -a spff 'bundle exec rspec --fail-fast'
abbr -a spfo 'bundle exec rspec --only-failures'
abbr -a sps 'bundle exec standard --fix'
abbr -a sp-s 'bundle exec rspec --exclude-pattern spec/system/**/*_spec.rb'
abbr -a spv 'bundle exec slim-lint app/**/*.slim && bundle exec erblint --lint-all'
abbr -a t tmux
abbr -a ta 'tmux attach'
abbr -a tat 'tmux attach -t '
abbr -a tl 'tmux list-sessions'
abbr -a tkss 'tmux kill-session -t '
abbr -a tksv 'tmux kill-server'
