# theme = "onedark"
# theme = "github_dark_dimmed"
theme = "everforest_dark"

[editor]
auto-format = true
auto-completion = true
bufferline = "multiple"
cursorline = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
line-number = "relative"
rulers = [120]

[editor.indent-guides]
render = true
# character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
character = "┊"
skip-levels = 1

[editor.file-picker]
hidden = false

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
esc = ["collapse_selection", "keep_primary_selection"]
# w = ["move_line_up", "scroll_up"]
# s = ["move_line_down", "scroll_down"]
# Inspired by https://theari.dev/blog/enhanced-helix-config/
"A-[" = "goto_previous_buffer"
"A-]" = "goto_next_buffer"
"A-w" = ":buffer-close"
"X" = ["extend_line_above"]

# [editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "none"

# [editor.whitespace.characters]
# nbsp = "⍽"
# tab = "→"
# newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

# [editor.auto-pairs]
# '(' = ')'
# '{' = '}'
# '[' = ']'
# '"' = '"'
# '`' = '`'
# '<' = '>'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.file-picker]
# hidden = false

[editor.statusline]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
# left = ["mode", "spinner", "total-line-numbers", "workspace-diagnostics", ]
# center = ["file-name"]
# right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
# separator = "│"

# [editor.lsp]
# display-messages = true
# auto-signature-help = true
# display-signature-help-docs = true
