[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

[[language]]
name = "erb"
language-servers = [ "emmet-ls" ]

[[language]]
name = "ruby"
formatter = { command = "bundle", args = ["exec", "standardrb", "--stdin", "foo.rb", "--fix", "--stderr"] }
auto-format = true

[[language]]
name = "erb"
formatter = { command = "htmlbeautifier", args = ["--keep-blank-lines", "1"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "standard", args = ["--stdin", "--fix"] }
auto-format = true
